name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag foophoof/sabnzbd:$(date +%s)
    - name: Log in to Docker Hub
      run: echo "${DOCKER_API_KEY}" | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_API_KEY: ${{ secrets.DOCKER_API_KEY }}
    - name: Push image to Docker Package Repo
      run: "docker push foophoof/sabnzbd"
